<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateColorsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('colors', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('name');
            $table->string('hex');
            $table->boolean('status')->default(0);
            $table->timestamps();
        });
        // array('id' =>1, 'name'=> "blue", 'hex'=> '#0000FF'),
        // array('id' =>2, 'name'=> "red", 'hex'=> '#FF0000'),
        // array('id' =>3, 'name'=> "green", 'hex'=> '#00FF00'),
        // array('id' =>4, 'name'=> "purple", 'hex'=> '#6A0DAD'),
        // array('id' =>5, 'name'=> "yellow", 'hex'=> '#FFFF00'),
        // array('id' =>6, 'name'=> "orange",'hex'=> '#FF7F00'),
        // array('id' =>7, 'name'=> "pink", 'hex'=> '#FFC0CB'),
        // array('id' =>8, 'name'=> "violet",'hex'=> '#8F00FF'),
        // array('id' =>9, 'name'=> "white", 'hex'=> '#FFFFFF'),
        // array('id' =>10, 'name'=> "black", 'hex'=> '#000000'),
        // array('id' =>11, 'name'=> "brown",'hex'=> '#88540B'),
        // array('id' =>12, 'name'=> "gray",'hex'=> '#B2BEB5'),
        // array('id' =>13, 'name'=> "teal",'hex'=> '#008080'),
        // array('id' =>14, 'name'=> "gold",'hex'=> '#A57C00'),
        // array('id' =>15, 'name'=> "crimson",'hex'=> '#DC143C'),
        // array('id' =>16, 'name'=> "Lemon", 'hex'=> '#FFF700')
        DB::table('colors')->insert(array(


            array('id' =>1, 'name'=> 'Absolute Zero', 'hex'=> '#0048BA'),
            array('id' =>2, 'name'=> 'Acid green', 'hex'=> '#B0BF1A'),
            array('id' =>3, 'name'=> 'Aero', 'hex'=> '#7CB9E8'),
            array('id' =>4, 'name'=> 'Aero blue', 'hex'=> '#C9FFE5'),
            array('id' =>5, 'name'=> 'African violet', 'hex'=> '#B284BE'),
            array('id' =>6, 'name'=> 'Air superiority blue', 'hex'=> '#72A0C1'),
            array('id' =>7, 'name'=> 'Alabaster', 'hex'=> '#EDEAE0'),
            array('id' =>8, 'name'=> 'Alice blue', 'hex'=> '#F0F8FF'),
            array('id' =>9, 'name'=> 'Alloy orange', 'hex'=> '#C46210'),
            array('id' =>10, 'name'=> 'Almond', 'hex'=> '#EFDECD'),
            array('id' =>11, 'name'=> 'Amaranth', 'hex'=> '#E52B50'),
            array('id' =>12, 'name'=> 'Amaranth-M&P', 'hex'=> '#9F2B68'),
            array('id' =>13, 'name'=> 'Amaranth pink', 'hex'=> '#F19CBB'),
            array('id' =>14, 'name'=> 'Amaranth purple', 'hex'=> '#AB274F'),
            array('id' =>15, 'name'=> 'Amaranth red', 'hex'=> '#D3212D'),
            array('id' =>16, 'name'=> 'Amazon', 'hex'=> '#3B7A57'),
            array('id' =>17, 'name'=> 'Amber', 'hex'=> '#FFBF00'),
            array('id' =>18, 'name'=> 'Amber-SAE/ECE', 'hex'=> '#FF7E00'),
            array('id' =>19, 'name'=> 'Amethyst', 'hex'=> '#9966CC'),
            array('id' =>20, 'name'=> 'Android green', 'hex'=> '#A4C639'),
            array('id' =>21, 'name'=> 'Antique brass', 'hex'=> '#CD9575'),
            array('id' =>22, 'name'=> 'Antique bronze', 'hex'=> '#665D1E'),
            array('id' =>23, 'name'=> 'Antique fuchsia', 'hex'=> '#915C83'),
            array('id' =>24, 'name'=> 'Antique ruby', 'hex'=> '#841B2D'),
            array('id' =>25, 'name'=> 'Antique white', 'hex'=> '#FAEBD7'),
            array('id' =>26, 'name'=> 'Ao-English', 'hex'=> '#008000'),
            array('id' =>27, 'name'=> 'Apple green', 'hex'=> '#8DB600'),
            array('id' =>28, 'name'=> 'Apricot', 'hex'=> '#FBCEB1'),
            array('id' =>29, 'name'=> 'Aqua', 'hex'=> '#00FFFF'),
            array('id' =>30, 'name'=> 'Aquamarine', 'hex'=> '#7FFFD4'),
            array('id' =>31, 'name'=> 'Arctic lime', 'hex'=> '#D0FF14'),
            array('id' =>32, 'name'=> 'Army green', 'hex'=> '#4B5320'),
            array('id' =>33, 'name'=> 'Artichoke', 'hex'=> '#8F9779'),
            array('id' =>34, 'name'=> 'Arylide yellow', 'hex'=> '#E9D66B'),
            array('id' =>35, 'name'=> 'Ash gray', 'hex'=> '#B2BEB5'),
            array('id' =>36, 'name'=> 'Asparagus', 'hex'=> '#87A96B'),
            array('id' =>37, 'name'=> 'Atomic tangerine', 'hex'=> '#FF9966'),
            array('id' =>38, 'name'=> 'Auburn', 'hex'=> '#A52A2A'),
            array('id' =>39, 'name'=> 'Aureolin', 'hex'=> '#FDEE00'),
            array('id' =>40, 'name'=> 'Avocado', 'hex'=> '#568203'),
            array('id' =>41, 'name'=> 'Azure', 'hex'=> '#007FFF'),
            array('id' =>42, 'name'=> 'Azure-X11/web color', 'hex'=> '#F0FFFF'),
            array('id' =>43, 'name'=> 'Baby blue', 'hex'=> '#89CFF0'),
            array('id' =>44, 'name'=> 'Baby blue eyes', 'hex'=> '#A1CAF1'),
            array('id' =>45, 'name'=> 'Baby pink', 'hex'=> '#F4C2C2'),
            array('id' =>46, 'name'=> 'Baby powder', 'hex'=> '#FEFEFA'),
            array('id' =>47, 'name'=> 'Baker-Miller pink', 'hex'=> '#FF91AF'),
            array('id' =>48, 'name'=> 'Banana Mania', 'hex'=> '#FAE7B5'),
            array('id' =>49, 'name'=> 'Barbie Pink', 'hex'=> '#DA1884'),
            array('id' =>50, 'name'=> 'Barn red', 'hex'=> '#7C0A02'),
            array('id' =>51, 'name'=> 'Battleship grey', 'hex'=> '#848482'),
            array('id' =>52, 'name'=> 'Beau blue', 'hex'=> '#BCD4E6'),
            array('id' =>53, 'name'=> 'Beaver', 'hex'=> '#9F8170'),
            array('id' =>54, 'name'=> 'Beige', 'hex'=> '#F5F5DC'),
            array('id' =>55, 'name'=> 'B-Dazzled blue', 'hex'=> '#2E5894'),
            array('id' =>56, 'name'=> 'Big dip o’ruby', 'hex'=> '#9C2542'),
            array('id' =>57, 'name'=> 'Bisque', 'hex'=> '#FFE4C4'),
            array('id' =>58, 'name'=> 'Bistre', 'hex'=> '#3D2B1F'),
            array('id' =>59, 'name'=> 'Bistre brown', 'hex'=> '#967117'),
            array('id' =>60, 'name'=> 'Bitter lemon', 'hex'=> '#CAE00D'),
            array('id' =>61, 'name'=> 'Bitter lime', 'hex'=> '#BFFF00'),
            array('id' =>62, 'name'=> 'Bittersweet', 'hex'=> '#FE6F5E'),
            array('id' =>63, 'name'=> 'Bittersweet shimmer', 'hex'=> '#BF4F51'),
            array('id' =>64, 'name'=> 'Black', 'hex'=> '#000000'),
            array('id' =>65, 'name'=> 'Black bean', 'hex'=> '#3D0C02'),
            array('id' =>66, 'name'=> 'Black chocolate', 'hex'=> '#1B1811'),
            array('id' =>67, 'name'=> 'Black coffee', 'hex'=> '#3B2F2F'),
            array('id' =>68, 'name'=> 'Black coral', 'hex'=> '#54626F'),
            array('id' =>69, 'name'=> 'Black olive', 'hex'=> '#3B3C36'),
            array('id' =>70, 'name'=> 'Black Shadows', 'hex'=> '#BFAFB2'),
            array('id' =>71, 'name'=> 'Blanched almond', 'hex'=> '#FFEBCD'),
            array('id' =>72, 'name'=> 'Blast-off bronze', 'hex'=> '#A57164'),
            array('id' =>73, 'name'=> 'Bleu de France', 'hex'=> '#318CE7'),
            array('id' =>74, 'name'=> 'Blizzard blue', 'hex'=> '#ACE5EE'),
            array('id' =>75, 'name'=> 'Blond', 'hex'=> '#FAF0BE'),
            array('id' =>76, 'name'=> 'Blood red', 'hex'=> '#660000'),
            array('id' =>77, 'name'=> 'Blue', 'hex'=> '#0000FF'),
            array('id' =>78, 'name'=> 'Blue-Crayola', 'hex'=> '#1F75FE'),
            array('id' =>79, 'name'=> 'Blue-Munsell', 'hex'=> '#0093AF'),
            array('id' =>80, 'name'=> 'Blue-NCS', 'hex'=> '#0087BD'),
            array('id' =>81, 'name'=> 'Blue-Pantone', 'hex'=> '#0018A8'),
            array('id' =>82, 'name'=> 'Blue-pigment', 'hex'=> '#333399'),
            array('id' =>83, 'name'=> 'Blue-RYB', 'hex'=> '#0247FE'),
            array('id' =>84, 'name'=> 'Blue bell', 'hex'=> '#A2A2D0'),
            array('id' =>85, 'name'=> 'Blue-gray', 'hex'=> '#6699CC'),
            array('id' =>86, 'name'=> 'Blue-green', 'hex'=> '#0D98BA'),
            array('id' =>87, 'name'=> 'Blue-green-color wheel', 'hex'=> '#064E40'),
            array('id' =>88, 'name'=> 'Blue jeans', 'hex'=> '#5DADEC'),
            array('id' =>89, 'name'=> 'Blue sapphire', 'hex'=> '#126180'),
            array('id' =>90, 'name'=> 'Blue-violet', 'hex'=> '#8A2BE2'),
            array('id' =>91, 'name'=> 'Blue-violet-Crayola', 'hex'=> '#7366BD'),
            array('id' =>92, 'name'=> 'Blue-violet-color wheel', 'hex'=> '#4D1A7F'),
            array('id' =>93, 'name'=> 'Blue yonder', 'hex'=> '#5072A7'),
            array('id' =>94, 'name'=> 'Bluetiful', 'hex'=> '#3C69E7'),
            array('id' =>95, 'name'=> 'Blush', 'hex'=> '#DE5D83'),
            array('id' =>96, 'name'=> 'Bole', 'hex'=> '#79443B'),
            array('id' =>97, 'name'=> 'Bone', 'hex'=> '#E3DAC9'),
            array('id' =>98, 'name'=> 'Bottle green', 'hex'=> '#006A4E'),
            array('id' =>99, 'name'=> 'Brandy', 'hex'=> '#87413F'),
            array('id' =>100, 'name'=> 'Brick red', 'hex'=> '#CB4154'),
            array('id' =>101, 'name'=> 'Bright green', 'hex'=> '#66FF00'),
            array('id' =>102, 'name'=> 'Bright lilac', 'hex'=> '#D891EF'),
            array('id' =>103, 'name'=> 'Bright maroon', 'hex'=> '#C32148'),
            array('id' =>104, 'name'=> 'Bright navy blue', 'hex'=> '#1974D2'),
            array('id' =>105, 'name'=> 'Bright yellow-Crayola', 'hex'=> '#FFAA1D'),
            array('id' =>106, 'name'=> 'Brilliant rose', 'hex'=> '#FF55A3'),
            array('id' =>107, 'name'=> 'Brink pink', 'hex'=> '#FB607F'),
            array('id' =>108, 'name'=> 'British racing green', 'hex'=> '#004225'),
            array('id' =>109, 'name'=> 'Bronze', 'hex'=> '#CD7F32'),
            array('id' =>110, 'name'=> 'Brown', 'hex'=> '#88540B'),
            array('id' =>111, 'name'=> 'Brown sugar', 'hex'=> '#AF6E4D'),
            array('id' =>112, 'name'=> 'Brunswick green', 'hex'=> '#1B4D3E'),
            array('id' =>113, 'name'=> 'Bud green', 'hex'=> '#7BB661'),
            array('id' =>114, 'name'=> 'Buff', 'hex'=> '#F0DC82'),
            array('id' =>115, 'name'=> 'Burgundy', 'hex'=> '#800020'),
            array('id' =>116, 'name'=> 'Burlywood', 'hex'=> '#DEB887'),
            array('id' =>117, 'name'=> 'Burnished brown', 'hex'=> '#A17A74'),
            array('id' =>118, 'name'=> 'Burnt orange', 'hex'=> '#CC5500'),
            array('id' =>119, 'name'=> 'Burnt sienna', 'hex'=> '#E97451'),
            array('id' =>120, 'name'=> 'Burnt umber', 'hex'=> '#8A3324'),
            array('id' =>121, 'name'=> 'Byzantine', 'hex'=> '#BD33A4'),
            array('id' =>122, 'name'=> 'Byzantium', 'hex'=> '#702963'),
            array('id' =>123, 'name'=> 'Cadet', 'hex'=> '#536872'),
            array('id' =>124, 'name'=> 'Cadet blue', 'hex'=> '#5F9EA0'),
            array('id' =>125, 'name'=> 'Cadet blue-Crayola', 'hex'=> '#A9B2C3'),
            array('id' =>126, 'name'=> 'Cadet grey', 'hex'=> '#91A3B0'),
            array('id' =>127, 'name'=> 'Cadmium green', 'hex'=> '#006B3C'),
            array('id' =>128, 'name'=> 'Cadmium orange', 'hex'=> '#ED872D'),
            array('id' =>129, 'name'=> 'Cadmium red', 'hex'=> '#E30022'),
            array('id' =>130, 'name'=> 'Cadmium yellow', 'hex'=> '#FFF600'),
            array('id' =>131, 'name'=> 'Café au lait', 'hex'=> '#A67B5B'),
            array('id' =>132, 'name'=> 'Café noir', 'hex'=> '#4B3621'),
            array('id' =>133, 'name'=> 'Cambridge blue', 'hex'=> '#A3C1AD'),
            array('id' =>134, 'name'=> 'Camel', 'hex'=> '#C19A6B'),
            array('id' =>135, 'name'=> 'Cameo pink', 'hex'=> '#EFBBCC'),
            array('id' =>136, 'name'=> 'Canary', 'hex'=> '#FFFF99'),
            array('id' =>137, 'name'=> 'Canary yellow', 'hex'=> '#FFEF00'),
            array('id' =>138, 'name'=> 'Candy apple red', 'hex'=> '#FF0800'),
            array('id' =>139, 'name'=> 'Candy pink', 'hex'=> '#E4717A'),
            array('id' =>140, 'name'=> 'Capri', 'hex'=> '#00BFFF'),
            array('id' =>141, 'name'=> 'Caput mortuum', 'hex'=> '#592720'),
            array('id' =>142, 'name'=> 'Cardinal', 'hex'=> '#C41E3A'),
            array('id' =>143, 'name'=> 'Caribbean green', 'hex'=> '#00CC99'),
            array('id' =>144, 'name'=> 'Carmine', 'hex'=> '#960018'),
            array('id' =>145, 'name'=> 'Carmine-M&P', 'hex'=> '#D70040'),
            array('id' =>146, 'name'=> 'Carnation pink', 'hex'=> '#FFA6C9'),
            array('id' =>147, 'name'=> 'Carnelian', 'hex'=> '#B31B1B'),
            array('id' =>148, 'name'=> 'Carolina blue', 'hex'=> '#56A0D3'),
            array('id' =>149, 'name'=> 'Carrot orange', 'hex'=> '#ED9121'),
            array('id' =>150, 'name'=> 'Castleton green', 'hex'=> '#00563F'),
            array('id' =>151, 'name'=> 'Catawba', 'hex'=> '#703642'),
            array('id' =>152, 'name'=> 'Cedar Chest', 'hex'=> '#C95A49'),
            array('id' =>153, 'name'=> 'Celadon', 'hex'=> '#ACE1AF'),
            array('id' =>154, 'name'=> 'Celadon blue', 'hex'=> '#007BA7'),
            array('id' =>155, 'name'=> 'Celadon green', 'hex'=> '#2F847C'),
            array('id' =>156, 'name'=> 'Celeste', 'hex'=> '#B2FFFF'),
            array('id' =>157, 'name'=> 'Celtic blue', 'hex'=> '#246BCE'),
            array('id' =>158, 'name'=> 'Cerise', 'hex'=> '#DE3163'),
            array('id' =>159, 'name'=> 'Cerulean', 'hex'=> '#007BA7'),
            array('id' =>160, 'name'=> 'Cerulean blue', 'hex'=> '#2A52BE'),
            array('id' =>161, 'name'=> 'Cerulean frost', 'hex'=> '#6D9BC3'),
            array('id' =>162, 'name'=> 'Cerulean-Crayola', 'hex'=> '#1DACD6'),
            array('id' =>163, 'name'=> 'CG blue', 'hex'=> '#007AA5'),
            array('id' =>164, 'name'=> 'CG red', 'hex'=> '#E03C31'),
            array('id' =>165, 'name'=> 'Champagne', 'hex'=> '#F7E7CE'),
            array('id' =>166, 'name'=> 'Champagne pink', 'hex'=> '#F1DDCF'),
            array('id' =>167, 'name'=> 'Charcoal', 'hex'=> '#36454F'),
            array('id' =>168, 'name'=> 'Charleston green', 'hex'=> '#232B2B'),
            array('id' =>169, 'name'=> 'Charm pink', 'hex'=> '#E68FAC'),
            array('id' =>170, 'name'=> 'Chartreuse-traditional', 'hex'=> '#DFFF00'),
            array('id' =>171, 'name'=> 'Chartreuse-web', 'hex'=> '#7FFF00'),
            array('id' =>172, 'name'=> 'Cherry blossom pink', 'hex'=> '#FFB7C5'),
            array('id' =>173, 'name'=> 'Chestnut', 'hex'=> '#954535'),
            array('id' =>174, 'name'=> 'China pink', 'hex'=> '#DE6FA1'),
            array('id' =>175, 'name'=> 'China rose', 'hex'=> '#A8516E'),
            array('id' =>176, 'name'=> 'Chinese red', 'hex'=> '#AA381E'),
            array('id' =>177, 'name'=> 'Chinese violet', 'hex'=> '#856088'),
            array('id' =>178, 'name'=> 'Chinese yellow', 'hex'=> '#FFB200'),
            array('id' =>179, 'name'=> 'Chocolate-traditional', 'hex'=> '#7B3F00'),
            array('id' =>180, 'name'=> 'Chocolate-web', 'hex'=> '#D2691E'),
            array('id' =>181, 'name'=> 'Chrome yellow', 'hex'=> '#FFA700'),
            array('id' =>182, 'name'=> 'Cinereous', 'hex'=> '#98817B'),
            array('id' =>183, 'name'=> 'Cinnabar', 'hex'=> '#E34234'),
            array('id' =>184, 'name'=> 'Cinnamon Satin', 'hex'=> '#CD607E'),
            array('id' =>185, 'name'=> 'Citrine', 'hex'=> '#E4D00A'),
            array('id' =>186, 'name'=> 'Citron', 'hex'=> '#9FA91F'),
            array('id' =>187, 'name'=> 'Claret', 'hex'=> '#7F1734'),
            array('id' =>188, 'name'=> 'Cobalt blue', 'hex'=> '#0047AB'),
            array('id' =>189, 'name'=> 'Cocoa brown', 'hex'=> '#D2691E'),
            array('id' =>190, 'name'=> 'Coffee', 'hex'=> '#6F4E37'),
            array('id' =>191, 'name'=> 'Columbia Blue', 'hex'=> '#B9D9EB'),
            array('id' =>192, 'name'=> 'Congo pink', 'hex'=> '#F88379'),
            array('id' =>193, 'name'=> 'Cool grey', 'hex'=> '#8C92AC'),
            array('id' =>194, 'name'=> 'Copper', 'hex'=> '#B87333'),
            array('id' =>195, 'name'=> 'Copper-Crayola', 'hex'=> '#DA8A67'),
            array('id' =>196, 'name'=> 'Copper penny', 'hex'=> '#AD6F69'),
            array('id' =>197, 'name'=> 'Copper red', 'hex'=> '#CB6D51'),
            array('id' =>198, 'name'=> 'Copper rose', 'hex'=> '#996666'),
            array('id' =>199, 'name'=> 'Coquelicot', 'hex'=> '#FF3800'),
            array('id' =>200, 'name'=> 'Coral', 'hex'=> '#FF7F50'),
            array('id' =>201, 'name'=> 'Coral pink', 'hex'=> '#F88379'),
            array('id' =>202, 'name'=> 'Cordovan', 'hex'=> '#893F45'),
            array('id' =>203, 'name'=> 'Corn', 'hex'=> '#FBEC5D'),
            array('id' =>204, 'name'=> 'Cornflower blue', 'hex'=> '#6495ED'),
            array('id' =>205, 'name'=> 'Cornsilk', 'hex'=> '#FFF8DC'),
            array('id' =>206, 'name'=> 'Cosmic cobalt', 'hex'=> '#2E2D88'),
            array('id' =>207, 'name'=> 'Cosmic latte', 'hex'=> '#FFF8E7'),
            array('id' =>208, 'name'=> 'Coyote brown', 'hex'=> '#81613C'),
            array('id' =>209, 'name'=> 'Cotton candy', 'hex'=> '#FFBCD9'),
            array('id' =>210, 'name'=> 'Cream', 'hex'=> '#FFFDD0'),
            array('id' =>211, 'name'=> 'Crimson', 'hex'=> '#DC143C'),
            array('id' =>212, 'name'=> 'Crimson-UA', 'hex'=> '#9E1B32'),
            array('id' =>213, 'name'=> 'Cultured', 'hex'=> '#F5F5F5'),
            array('id' =>214, 'name'=> 'Cyan', 'hex'=> '#00FFFF'),
            array('id' =>215, 'name'=> 'Cyan-process', 'hex'=> '#00B7EB'),
            array('id' =>216, 'name'=> 'Cyber grape', 'hex'=> '#58427C'),
            array('id' =>217, 'name'=> 'Cyber yellow', 'hex'=> '#FFD300'),
            array('id' =>218, 'name'=> 'Cyclamen', 'hex'=> '#F56FA1'),
            array('id' =>219, 'name'=> 'Dark blue-gray', 'hex'=> '#666699'),
            array('id' =>220, 'name'=> 'Dark brown', 'hex'=> '#654321'),
            array('id' =>221, 'name'=> 'Dark byzantium', 'hex'=> '#5D3954'),
            array('id' =>222, 'name'=> 'Dark cornflower blue', 'hex'=> '#26428B'),
            array('id' =>223, 'name'=> 'Dark cyan', 'hex'=> '#008B8B'),
            array('id' =>224, 'name'=> 'Dark electric blue', 'hex'=> '#536878'),
            array('id' =>225, 'name'=> 'Dark goldenrod', 'hex'=> '#B8860B'),
            array('id' =>226, 'name'=> 'Dark green', 'hex'=> '#013220'),
            array('id' =>227, 'name'=> 'Dark green-X11', 'hex'=> '#006400'),
            array('id' =>228, 'name'=> 'Dark jungle green', 'hex'=> '#1A2421'),
            array('id' =>229, 'name'=> 'Dark khaki', 'hex'=> '#BDB76B'),
            array('id' =>230, 'name'=> 'Dark lava', 'hex'=> '#483C32'),
            array('id' =>231, 'name'=> 'Dark liver', 'hex'=> '#534B4F'),
            array('id' =>232, 'name'=> 'Dark liver-horses', 'hex'=> '#543D37'),
            array('id' =>233, 'name'=> 'Dark magenta', 'hex'=> '#8B008B'),
            array('id' =>234, 'name'=> 'Dark moss green', 'hex'=> '#4A5D23'),
            array('id' =>235, 'name'=> 'Dark olive green', 'hex'=> '#556B2F'),
            array('id' =>236, 'name'=> 'Dark orange', 'hex'=> '#FF8C00'),
            array('id' =>237, 'name'=> 'Dark orchid', 'hex'=> '#9932CC'),
            array('id' =>238, 'name'=> 'Dark pastel green', 'hex'=> '#03C03C'),
            array('id' =>239, 'name'=> 'Dark purple', 'hex'=> '#301934'),
            array('id' =>240, 'name'=> 'Dark red', 'hex'=> '#8B0000'),
            array('id' =>241, 'name'=> 'Dark salmon', 'hex'=> '#E9967A'),
            array('id' =>242, 'name'=> 'Dark sea green', 'hex'=> '#8FBC8F'),
            array('id' =>243, 'name'=> 'Dark sienna', 'hex'=> '#3C1414'),
            array('id' =>244, 'name'=> 'Dark sky blue', 'hex'=> '#8CBED6'),
            array('id' =>245, 'name'=> 'Dark slate blue', 'hex'=> '#483D8B'),
            array('id' =>246, 'name'=> 'Dark slate gray', 'hex'=> '#2F4F4F'),
            array('id' =>247, 'name'=> 'Dark spring green', 'hex'=> '#177245'),
            array('id' =>248, 'name'=> 'Dark turquoise', 'hex'=> '#00CED1'),
            array('id' =>249, 'name'=> 'Dark violet', 'hex'=> '#9400D3'),
            array('id' =>250, 'name'=> 'Dartmouth green', 'hex'=> '#00703C'),
            array('id' =>251, 'name'=> 'Davy S grey', 'hex'=> '#555555'),
            array('id' =>252, 'name'=> 'Deep cerise', 'hex'=> '#DA3287'),
            array('id' =>253, 'name'=> 'Deep champagne', 'hex'=> '#FAD6A5'),
            array('id' =>254, 'name'=> 'Deep chestnut', 'hex'=> '#B94E48'),
            array('id' =>255, 'name'=> 'Deep jungle green', 'hex'=> '#004B49'),
            array('id' =>256, 'name'=> 'Deep pink', 'hex'=> '#FF1493'),
            array('id' =>257, 'name'=> 'Deep saffron', 'hex'=> '#FF9933'),
            array('id' =>258, 'name'=> 'Deep sky blue', 'hex'=> '#00BFFF'),
            array('id' =>259, 'name'=> 'Deep Space Sparkle', 'hex'=> '#4A646C'),
            array('id' =>260, 'name'=> 'Deep taupe', 'hex'=> '#7E5E60'),
            array('id' =>261, 'name'=> 'Denim', 'hex'=> '#1560BD'),
            array('id' =>262, 'name'=> 'Denim blue', 'hex'=> '#2243B6'),
            array('id' =>263, 'name'=> 'Desert', 'hex'=> '#C19A6B'),
            array('id' =>264, 'name'=> 'Desert sand', 'hex'=> '#EDC9AF'),
            array('id' =>265, 'name'=> 'Dim gray', 'hex'=> '#696969'),
            array('id' =>266, 'name'=> 'Dodger blue', 'hex'=> '#1E90FF'),
            array('id' =>267, 'name'=> 'Dogwood rose', 'hex'=> '#D71868'),
            array('id' =>268, 'name'=> 'Drab', 'hex'=> '#967117'),
            array('id' =>269, 'name'=> 'Duke blue', 'hex'=> '#00009C'),
            array('id' =>270, 'name'=> 'Dutch white', 'hex'=> '#EFDFBB'),
            array('id' =>271, 'name'=> 'Earth yellow', 'hex'=> '#E1A95F'),
            array('id' =>272, 'name'=> 'Ebony', 'hex'=> '#555D50'),
            array('id' =>273, 'name'=> 'Ecru', 'hex'=> '#C2B280'),
            array('id' =>274, 'name'=> 'Eerie black', 'hex'=> '#1B1B1B'),
            array('id' =>275, 'name'=> 'Eggplant', 'hex'=> '#614051'),
            array('id' =>276, 'name'=> 'Eggshell', 'hex'=> '#F0EAD6'),
            array('id' =>277, 'name'=> 'Egyptian blue', 'hex'=> '#1034A6'),
            array('id' =>278, 'name'=> 'Electric blue', 'hex'=> '#7DF9FF'),
            array('id' =>279, 'name'=> 'Electric green', 'hex'=> '#00FF00'),
            array('id' =>280, 'name'=> 'Electric indigo', 'hex'=> '#6F00FF'),
            array('id' =>281, 'name'=> 'Electric lime', 'hex'=> '#CCFF00'),
            array('id' =>282, 'name'=> 'Electric purple', 'hex'=> '#BF00FF'),
            array('id' =>283, 'name'=> 'Electric violet', 'hex'=> '#8F00FF'),
            array('id' =>284, 'name'=> 'Emerald', 'hex'=> '#50C878'),
            array('id' =>285, 'name'=> 'Eminence', 'hex'=> '#6C3082'),
            array('id' =>286, 'name'=> 'English green', 'hex'=> '#1B4D3E'),
            array('id' =>287, 'name'=> 'English lavender', 'hex'=> '#B48395'),
            array('id' =>288, 'name'=> 'English red', 'hex'=> '#AB4B52'),
            array('id' =>289, 'name'=> 'English vermillion', 'hex'=> '#CC474B'),
            array('id' =>290, 'name'=> 'English violet', 'hex'=> '#563C5C'),
            array('id' =>291, 'name'=> 'Erin', 'hex'=> '#00FF40'),
            array('id' =>292, 'name'=> 'Eton blue', 'hex'=> '#96C8A2'),
            array('id' =>293, 'name'=> 'Fallow', 'hex'=> '#C19A6B'),
            array('id' =>294, 'name'=> 'Falu red', 'hex'=> '#801818'),
            array('id' =>295, 'name'=> 'Fandango', 'hex'=> '#B53389'),
            array('id' =>296, 'name'=> 'Fandango pink', 'hex'=> '#DE5285'),
            array('id' =>297, 'name'=> 'Fashion fuchsia', 'hex'=> '#F400A1'),
            array('id' =>298, 'name'=> 'Fawn', 'hex'=> '#E5AA70'),
            array('id' =>299, 'name'=> 'Feldgrau', 'hex'=> '#4D5D53'),
            array('id' =>300, 'name'=> 'Fern green', 'hex'=> '#4F7942'),
            array('id' =>301, 'name'=> 'Field drab', 'hex'=> '#6C541E'),
            array('id' =>302, 'name'=> 'Fiery rose', 'hex'=> '#FF5470'),
            array('id' =>303, 'name'=> 'Firebrick', 'hex'=> '#B22222'),
            array('id' =>304, 'name'=> 'Fire engine red', 'hex'=> '#CE2029'),
            array('id' =>305, 'name'=> 'Fire opal', 'hex'=> '#E95C4B'),
            array('id' =>306, 'name'=> 'Flame', 'hex'=> '#E25822'),
            array('id' =>307, 'name'=> 'Flax', 'hex'=> '#EEDC82'),
            array('id' =>308, 'name'=> 'Flickr Blue', 'hex'=> '#0063dc'),
            array('id' =>309, 'name'=> 'Flickr Pink', 'hex'=> '#FB0081'),
            array('id' =>310, 'name'=> 'Flirt', 'hex'=> '#A2006D'),
            array('id' =>311, 'name'=> 'Floral white', 'hex'=> '#FFFAF0'),
            array('id' =>312, 'name'=> 'Fluorescent blue', 'hex'=> '#15F4EE'),
            array('id' =>313, 'name'=> 'Forest green-Crayola', 'hex'=> '#5FA777'),
            array('id' =>314, 'name'=> 'Forest green-traditional', 'hex'=> '#014421'),
            array('id' =>315, 'name'=> 'Forest green-web', 'hex'=> '#228B22'),
            array('id' =>316, 'name'=> 'French beige', 'hex'=> '#A67B5B'),
            array('id' =>317, 'name'=> 'French bistre', 'hex'=> '#856D4D'),
            array('id' =>318, 'name'=> 'French blue', 'hex'=> '#0072BB'),
            array('id' =>319, 'name'=> 'French fuchsia', 'hex'=> '#FD3F92'),
            array('id' =>320, 'name'=> 'French lilac', 'hex'=> '#86608E'),
            array('id' =>321, 'name'=> 'French lime', 'hex'=> '#9EFD38'),
            array('id' =>322, 'name'=> 'French mauve', 'hex'=> '#D473D4'),
            array('id' =>323, 'name'=> 'French pink', 'hex'=> '#FD6C9E'),
            array('id' =>324, 'name'=> 'French raspberry', 'hex'=> '#C72C48'),
            array('id' =>325, 'name'=> 'French rose', 'hex'=> '#F64A8A'),
            array('id' =>326, 'name'=> 'French sky blue', 'hex'=> '#77B5FE'),
            array('id' =>327, 'name'=> 'French violet', 'hex'=> '#8806CE'),
            array('id' =>328, 'name'=> 'Frostbite', 'hex'=> '#E936A7'),
            array('id' =>329, 'name'=> 'Fuchsia', 'hex'=> '#FF00FF'),
            array('id' =>330, 'name'=> 'Fuchsia-Crayola', 'hex'=> '#C154C1'),
            array('id' =>331, 'name'=> 'Fuchsia purple', 'hex'=> '#CC397B'),
            array('id' =>332, 'name'=> 'Fuchsia rose', 'hex'=> '#C74375'),
            array('id' =>333, 'name'=> 'Fulvous', 'hex'=> '#E48400'),
            array('id' =>334, 'name'=> 'Fuzzy Wuzzy', 'hex'=> '#87421F'),
            array('id' =>335, 'name'=> 'Gainsboro', 'hex'=> '#DCDCDC'),
            array('id' =>336, 'name'=> 'Gamboge', 'hex'=> '#E49B0F'),
            array('id' =>337, 'name'=> 'Generic viridian', 'hex'=> '#007F66'),
            array('id' =>338, 'name'=> 'Ghost white', 'hex'=> '#F8F8FF'),
            array('id' =>339, 'name'=> 'Glaucous', 'hex'=> '#6082B6'),
            array('id' =>340, 'name'=> 'Glossy grape', 'hex'=> '#AB92B3'),
            array('id' =>341, 'name'=> 'GO green', 'hex'=> '#00AB66'),
            array('id' =>342, 'name'=> 'Gold', 'hex'=> '#A57C00'),
            array('id' =>343, 'name'=> 'Gold-metallic', 'hex'=> '#D4AF37'),
            array('id' =>344, 'name'=> 'Gold-web-Golden', 'hex'=> '#FFD700'),
            array('id' =>345, 'name'=> 'Gold-Crayola', 'hex'=> '#E6BE8A'),
            array('id' =>346, 'name'=> 'Gold Fusion', 'hex'=> '#85754E'),
            array('id' =>347, 'name'=> 'Golden brown', 'hex'=> '#996515'),
            array('id' =>348, 'name'=> 'Golden poppy', 'hex'=> '#FCC200'),
            array('id' =>349, 'name'=> 'Golden yellow', 'hex'=> '#FFDF00'),
            array('id' =>350, 'name'=> 'Goldenrod', 'hex'=> '#DAA520'),
            array('id' =>351, 'name'=> 'Granite gray', 'hex'=> '#676767'),
            array('id' =>352, 'name'=> 'Granny Smith apple', 'hex'=> '#A8E4A0'),
            array('id' =>353, 'name'=> 'Gray-web', 'hex'=> '#808080'),
            array('id' =>354, 'name'=> 'Gray-X11 gray', 'hex'=> '#BEBEBE'),
            array('id' =>355, 'name'=> 'Green', 'hex'=> '#00FF00'),
            array('id' =>356, 'name'=> 'Green-Crayola', 'hex'=> '#1CAC78'),
            array('id' =>357, 'name'=> 'Green-web', 'hex'=> '#008000'),
            array('id' =>358, 'name'=> 'Green-Munsell', 'hex'=> '#00A877'),
            array('id' =>359, 'name'=> 'Green-NCS', 'hex'=> '#009F6B'),
            array('id' =>360, 'name'=> 'Green-Pantone', 'hex'=> '#00AD43'),
            array('id' =>361, 'name'=> 'Green-pigment', 'hex'=> '#00A550'),
            array('id' =>362, 'name'=> 'Green-RYB', 'hex'=> '#66B032'),
            array('id' =>363, 'name'=> 'Green-blue', 'hex'=> '#1164B4'),
            array('id' =>364, 'name'=> 'Green-blue-Crayola', 'hex'=> '#2887C8'),
            array('id' =>365, 'name'=> 'Green-cyan', 'hex'=> '#009966'),
            array('id' =>366, 'name'=> 'Green Lizard', 'hex'=> '#A7F432'),
            array('id' =>367, 'name'=> 'Green Sheen', 'hex'=> '#6EAEA1'),
            array('id' =>368, 'name'=> 'Green-yellow', 'hex'=> '#ADFF2F'),
            array('id' =>369, 'name'=> 'Green-yellow-Crayola', 'hex'=> '#F0E891'),
            array('id' =>370, 'name'=> 'Grullo', 'hex'=> '#A99A86'),
            array('id' =>371, 'name'=> 'Gunmetal', 'hex'=> '#2a3439'),
            array('id' =>372, 'name'=> 'Han blue', 'hex'=> '#446CCF'),
            array('id' =>373, 'name'=> 'Han purple', 'hex'=> '#5218FA'),
            array('id' =>374, 'name'=> 'Hansa yellow', 'hex'=> '#E9D66B'),
            array('id' =>375, 'name'=> 'Harlequin', 'hex'=> '#3FFF00'),
            array('id' =>376, 'name'=> 'Harvest gold', 'hex'=> '#DA9100'),
            array('id' =>377, 'name'=> 'Heat Wave', 'hex'=> '#FF7A00'),
            array('id' =>378, 'name'=> 'Heliotrope', 'hex'=> '#DF73FF'),
            array('id' =>379, 'name'=> 'Heliotrope gray', 'hex'=> '#AA98A9'),
            array('id' =>380, 'name'=> 'Hollywood cerise', 'hex'=> '#F400A1'),
            array('id' =>381, 'name'=> 'Honeydew', 'hex'=> '#F0FFF0'),
            array('id' =>382, 'name'=> 'Honolulu blue', 'hex'=> '#006DB0'),
            array('id' =>383, 'name'=> 'Hooker S green', 'hex'=> '#49796B'),
            array('id' =>384, 'name'=> 'Hot magenta', 'hex'=> '#FF1DCE'),
            array('id' =>385, 'name'=> 'Hot pink', 'hex'=> '#FF69B4'),
            array('id' =>386, 'name'=> 'Hunter green', 'hex'=> '#355E3B'),
            array('id' =>387, 'name'=> 'Iceberg', 'hex'=> '#71A6D2'),
            array('id' =>388, 'name'=> 'Icterine', 'hex'=> '#FCF75E'),
            array('id' =>389, 'name'=> 'Illuminating emerald', 'hex'=> '#319177'),
            array('id' =>390, 'name'=> 'Imperial red', 'hex'=> '#ED2939'),
            array('id' =>391, 'name'=> 'Inchworm', 'hex'=> '#B2EC5D'),
            array('id' =>392, 'name'=> 'Independence', 'hex'=> '#4C516D'),
            array('id' =>393, 'name'=> 'India green', 'hex'=> '#138808'),
            array('id' =>394, 'name'=> 'Indian red', 'hex'=> '#CD5C5C'),
            array('id' =>395, 'name'=> 'Indian yellow', 'hex'=> '#E3A857'),
            array('id' =>396, 'name'=> 'Indigo', 'hex'=> '#4B0082'),
            array('id' =>397, 'name'=> 'Indigo dye', 'hex'=> '#00416A'),
            array('id' =>398, 'name'=> 'International Klein Blue', 'hex'=> '#002FA7'),
            array('id' =>399, 'name'=> 'International orange-aerospace', 'hex'=> '#FF4F00'),
            array('id' =>400, 'name'=> 'International orange-engineering', 'hex'=> '#BA160C'),
            array('id' =>401, 'name'=> 'International orange-Golden Gate Bridge', 'hex'=> '#C0362C'),
            array('id' =>402, 'name'=> 'Iris', 'hex'=> '#5A4FCF'),
            array('id' =>403, 'name'=> 'Irresistible', 'hex'=> '#B3446C'),
            array('id' =>404, 'name'=> 'Isabelline', 'hex'=> '#F4F0EC'),
            array('id' =>405, 'name'=> 'Italian sky blue', 'hex'=> '#B2FFFF'),
            array('id' =>406, 'name'=> 'Ivory', 'hex'=> '#FFFFF0'),
            array('id' =>407, 'name'=> 'Jade', 'hex'=> '#00A86B'),
            array('id' =>408, 'name'=> 'Jasmine', 'hex'=> '#F8DE7E'),
            array('id' =>409, 'name'=> 'Jazzberry jam', 'hex'=> '#A50B5E'),
            array('id' =>410, 'name'=> 'Jet', 'hex'=> '#343434'),
            array('id' =>411, 'name'=> 'Jonquil', 'hex'=> '#F4CA16'),
            array('id' =>412, 'name'=> 'June bud', 'hex'=> '#BDDA57'),
            array('id' =>413, 'name'=> 'Jungle green', 'hex'=> '#29AB87'),
            array('id' =>414, 'name'=> 'Kelly green', 'hex'=> '#4CBB17'),
            array('id' =>415, 'name'=> 'Keppel', 'hex'=> '#3AB09E'),
            array('id' =>416, 'name'=> 'Key lime', 'hex'=> '#E8F48C'),
            array('id' =>417, 'name'=> 'Khaki-web', 'hex'=> '#C3B091'),
            array('id' =>418, 'name'=> 'Khaki-X11-Light khaki', 'hex'=> '#F0E68C'),
            array('id' =>419, 'name'=> 'Kobe', 'hex'=> '#882D17'),
            array('id' =>420, 'name'=> 'Kobi', 'hex'=> '#E79FC4'),
            array('id' =>421, 'name'=> 'Kobicha', 'hex'=> '#6B4423'),
            array('id' =>422, 'name'=> 'Kombu green', 'hex'=> '#354230'),
            array('id' =>423, 'name'=> 'KSU purple', 'hex'=> '#512888'),
            array('id' =>424, 'name'=> 'Languid lavender', 'hex'=> '#D6CADD'),
            array('id' =>425, 'name'=> 'Lapis lazuli', 'hex'=> '#26619C'),
            array('id' =>426, 'name'=> 'Laser lemon', 'hex'=> '#FFFF66'),
            array('id' =>427, 'name'=> 'Laurel green', 'hex'=> '#A9BA9D'),
            array('id' =>428, 'name'=> 'Lava', 'hex'=> '#CF1020'),
            array('id' =>429, 'name'=> 'Lavender-floral', 'hex'=> '#B57EDC'),
            array('id' =>430, 'name'=> 'Lavender-web', 'hex'=> '#E6E6FA'),
            array('id' =>431, 'name'=> 'Lavender blue', 'hex'=> '#CCCCFF'),
            array('id' =>432, 'name'=> 'Lavender blush', 'hex'=> '#FFF0F5'),
            array('id' =>433, 'name'=> 'Lavender gray', 'hex'=> '#C4C3D0'),
            array('id' =>434, 'name'=> 'Lawn green', 'hex'=> '#7CFC00'),
            array('id' =>435, 'name'=> 'Lemon', 'hex'=> '#FFF700'),
            array('id' =>436, 'name'=> 'Lemon chiffon', 'hex'=> '#FFFACD'),
            array('id' =>437, 'name'=> 'Lemon curry', 'hex'=> '#CCA01D'),
            array('id' =>438, 'name'=> 'Lemon glacier', 'hex'=> '#FDFF00'),
            array('id' =>439, 'name'=> 'Lemon meringue', 'hex'=> '#F6EABE'),
            array('id' =>440, 'name'=> 'Lemon yellow', 'hex'=> '#FFF44F'),
            array('id' =>441, 'name'=> 'Lemon yellow-Crayola', 'hex'=> '#FFFF9F'),
            array('id' =>442, 'name'=> 'Liberty', 'hex'=> '#545AA7'),
            array('id' =>443, 'name'=> 'Light blue', 'hex'=> '#ADD8E6'),
            array('id' =>444, 'name'=> 'Light coral', 'hex'=> '#F08080'),
            array('id' =>445, 'name'=> 'Light cornflower blue', 'hex'=> '#93CCEA'),
            array('id' =>446, 'name'=> 'Light cyan', 'hex'=> '#E0FFFF'),
            array('id' =>447, 'name'=> 'Light French beige', 'hex'=> '#C8AD7F'),
            array('id' =>448, 'name'=> 'Light goldenrod yellow', 'hex'=> '#FAFAD2'),
            array('id' =>449, 'name'=> 'Light gray', 'hex'=> '#D3D3D3'),
            array('id' =>450, 'name'=> 'Light green', 'hex'=> '#90EE90'),
            array('id' =>451, 'name'=> 'Light orange', 'hex'=> '#FED8B1'),
            array('id' =>452, 'name'=> 'Light periwinkle', 'hex'=> '#C5CBE1'),
            array('id' =>453, 'name'=> 'Light pink', 'hex'=> '#FFB6C1'),
            array('id' =>454, 'name'=> 'Light salmon', 'hex'=> '#FFA07A'),
            array('id' =>455, 'name'=> 'Light sea green', 'hex'=> '#20B2AA'),
            array('id' =>456, 'name'=> 'Light sky blue', 'hex'=> '#87CEFA'),
            array('id' =>457, 'name'=> 'Light slate gray', 'hex'=> '#778899'),
            array('id' =>458, 'name'=> 'Light steel blue', 'hex'=> '#B0C4DE'),
            array('id' =>459, 'name'=> 'Light yellow', 'hex'=> '#FFFFE0'),
            array('id' =>460, 'name'=> 'Lilac', 'hex'=> '#C8A2C8'),
            array('id' =>461, 'name'=> 'Lilac Luster', 'hex'=> '#AE98AA'),
            array('id' =>462, 'name'=> 'Lime-color wheel', 'hex'=> '#BFFF00'),
            array('id' =>463, 'name'=> 'Lime-web-X11 green', 'hex'=> '#00FF00'),
            array('id' =>464, 'name'=> 'Lime green', 'hex'=> '#32CD32'),
            array('id' =>465, 'name'=> 'Lincoln green', 'hex'=> '#195905'),
            array('id' =>466, 'name'=> 'Linen', 'hex'=> '#FAF0E6'),
            array('id' =>467, 'name'=> 'Lion', 'hex'=> '#C19A6B'),
            array('id' =>468, 'name'=> 'Liseran purple', 'hex'=> '#DE6FA1'),
            array('id' =>469, 'name'=> 'Little boy blue', 'hex'=> '#6CA0DC'),
            array('id' =>470, 'name'=> 'Liver', 'hex'=> '#674C47'),
            array('id' =>471, 'name'=> 'Liver-dogs', 'hex'=> '#B86D29'),
            array('id' =>472, 'name'=> 'Liver-organ', 'hex'=> '#6C2E1F'),
            array('id' =>473, 'name'=> 'Liver chestnut', 'hex'=> '#987456'),
            array('id' =>474, 'name'=> 'Livid', 'hex'=> '#6699CC'),
            array('id' =>475, 'name'=> 'Macaroni and Cheese', 'hex'=> '#FFBD88'),
            array('id' =>476, 'name'=> 'Madder Lake', 'hex'=> '#CC3336'),
            array('id' =>477, 'name'=> 'Magenta', 'hex'=> '#FF00FF'),
            array('id' =>478, 'name'=> 'Magenta-Crayola', 'hex'=> '#F653A6'),
            array('id' =>479, 'name'=> 'Magenta-dye', 'hex'=> '#CA1F7B'),
            array('id' =>480, 'name'=> 'Magenta-Pantone', 'hex'=> '#D0417E'),
            array('id' =>481, 'name'=> 'Magenta-process', 'hex'=> '#FF0090'),
            array('id' =>482, 'name'=> 'Magenta haze', 'hex'=> '#9F4576'),
            array('id' =>483, 'name'=> 'Magic mint', 'hex'=> '#AAF0D1'),
            array('id' =>484, 'name'=> 'Magnolia', 'hex'=> '#F8F4FF'),
            array('id' =>485, 'name'=> 'Mahogany', 'hex'=> '#C04000'),
            array('id' =>486, 'name'=> 'Maize', 'hex'=> '#FBEC5D'),
            array('id' =>487, 'name'=> 'Maize-Crayola', 'hex'=> '#F2C649'),
            array('id' =>488, 'name'=> 'Majorelle blue', 'hex'=> '#6050DC'),
            array('id' =>489, 'name'=> 'Malachite', 'hex'=> '#0BDA51'),
            array('id' =>490, 'name'=> 'Manatee', 'hex'=> '#979AAA'),
            array('id' =>491, 'name'=> 'Mandarin', 'hex'=> '#F37A48'),
            array('id' =>492, 'name'=> 'Mango', 'hex'=> '#FDBE02'),
            array('id' =>493, 'name'=> 'Mango Tango', 'hex'=> '#FF8243'),
            array('id' =>494, 'name'=> 'Mantis', 'hex'=> '#74C365'),
            array('id' =>495, 'name'=> 'Mardi Gras', 'hex'=> '#880085'),
            array('id' =>496, 'name'=> 'Marigold', 'hex'=> '#EAA221'),
            array('id' =>497, 'name'=> 'Maroon-Crayola', 'hex'=> '#C32148'),
            array('id' =>498, 'name'=> 'Maroon-web', 'hex'=> '#800000'),
            array('id' =>499, 'name'=> 'Maroon-X11', 'hex'=> '#B03060'),
            array('id' =>500, 'name'=> 'Mauve', 'hex'=> '#E0B0FF'),
            array('id' =>501, 'name'=> 'Mauve taupe', 'hex'=> '#915F6D'),
            array('id' =>502, 'name'=> 'Mauvelous', 'hex'=> '#EF98AA'),
            array('id' =>503, 'name'=> 'Maximum blue', 'hex'=> '#47ABCC'),
            array('id' =>504, 'name'=> 'Maximum blue green', 'hex'=> '#30BFBF'),
            array('id' =>505, 'name'=> 'Maximum blue purple', 'hex'=> '#ACACE6'),
            array('id' =>506, 'name'=> 'Maximum green', 'hex'=> '#5E8C31'),
            array('id' =>507, 'name'=> 'Maximum green yellow', 'hex'=> '#D9E650'),
            array('id' =>508, 'name'=> 'Maximum purple', 'hex'=> '#733380'),
            array('id' =>509, 'name'=> 'Maximum red', 'hex'=> '#D92121'),
            array('id' =>510, 'name'=> 'Maximum red purple', 'hex'=> '#A63A79'),
            array('id' =>511, 'name'=> 'Maximum yellow', 'hex'=> '#FAFA37'),
            array('id' =>512, 'name'=> 'Maximum yellow red', 'hex'=> '#F2BA49'),
            array('id' =>513, 'name'=> 'May green', 'hex'=> '#4C9141'),
            array('id' =>514, 'name'=> 'Maya blue', 'hex'=> '#73C2FB'),
            array('id' =>515, 'name'=> 'Medium aquamarine', 'hex'=> '#66DDAA'),
            array('id' =>516, 'name'=> 'Medium blue', 'hex'=> '#0000CD'),
            array('id' =>517, 'name'=> 'Medium candy apple red', 'hex'=> '#E2062C'),
            array('id' =>518, 'name'=> 'Medium carmine', 'hex'=> '#AF4035'),
            array('id' =>519, 'name'=> 'Medium champagne', 'hex'=> '#F3E5AB'),
            array('id' =>520, 'name'=> 'Medium orchid', 'hex'=> '#BA55D3'),
            array('id' =>521, 'name'=> 'Medium purple', 'hex'=> '#9370DB'),
            array('id' =>522, 'name'=> 'Medium sea green', 'hex'=> '#3CB371'),
            array('id' =>523, 'name'=> 'Medium slate blue', 'hex'=> '#7B68EE'),
            array('id' =>524, 'name'=> 'Medium spring green', 'hex'=> '#00FA9A'),
            array('id' =>525, 'name'=> 'Medium turquoise', 'hex'=> '#48D1CC'),
            array('id' =>526, 'name'=> 'Medium violet-red', 'hex'=> '#C71585'),
            array('id' =>527, 'name'=> 'Mellow apricot', 'hex'=> '#F8B878'),
            array('id' =>528, 'name'=> 'Mellow yellow', 'hex'=> '#F8DE7E'),
            array('id' =>529, 'name'=> 'Melon', 'hex'=> '#FEBAAD'),
            array('id' =>530, 'name'=> 'Metallic gold', 'hex'=> '#D3AF37'),
            array('id' =>531, 'name'=> 'Metallic Seaweed', 'hex'=> '#0A7E8C'),
            array('id' =>532, 'name'=> 'Metallic Sunburst', 'hex'=> '#9C7C38'),
            array('id' =>533, 'name'=> 'Mexican pink', 'hex'=> '#E4007C'),
            array('id' =>534, 'name'=> 'Middle blue', 'hex'=> '#7ED4E6'),
            array('id' =>535, 'name'=> 'Middle blue green', 'hex'=> '#8DD9CC'),
            array('id' =>536, 'name'=> 'Middle blue purple', 'hex'=> '#8B72BE'),
            array('id' =>537, 'name'=> 'Middle grey', 'hex'=> '#8B8680'),
            array('id' =>538, 'name'=> 'Middle green', 'hex'=> '#4D8C57'),
            array('id' =>539, 'name'=> 'Middle green yellow', 'hex'=> '#ACBF60'),
            array('id' =>540, 'name'=> 'Middle purple', 'hex'=> '#D982B5'),
            array('id' =>541, 'name'=> 'Middle red', 'hex'=> '#E58E73'),
            array('id' =>542, 'name'=> 'Middle red purple', 'hex'=> '#A55353'),
            array('id' =>543, 'name'=> 'Middle yellow', 'hex'=> '#FFEB00'),
            array('id' =>544, 'name'=> 'Middle yellow red', 'hex'=> '#ECB176'),
            array('id' =>545, 'name'=> 'Midnight', 'hex'=> '#702670'),
            array('id' =>546, 'name'=> 'Midnight blue', 'hex'=> '#191970'),
            array('id' =>547, 'name'=> 'Midnight green-eagle green', 'hex'=> '#004953'),
            array('id' =>548, 'name'=> 'Mikado yellow', 'hex'=> '#FFC40C'),
            array('id' =>549, 'name'=> 'Mimi pink', 'hex'=> '#FFDAE9'),
            array('id' =>550, 'name'=> 'Mindaro', 'hex'=> '#E3F988'),
            array('id' =>551, 'name'=> 'Ming', 'hex'=> '#36747D'),
            array('id' =>552, 'name'=> 'Minion yellow', 'hex'=> '#F5E050'),
            array('id' =>553, 'name'=> 'Mint', 'hex'=> '#3EB489'),
            array('id' =>554, 'name'=> 'Mint cream', 'hex'=> '#F5FFFA'),
            array('id' =>555, 'name'=> 'Mint green', 'hex'=> '#98FF98'),
            array('id' =>556, 'name'=> 'Misty moss', 'hex'=> '#BBB477'),
            array('id' =>557, 'name'=> 'Misty rose', 'hex'=> '#FFE4E1'),
            array('id' =>558, 'name'=> 'Mode beige', 'hex'=> '#967117'),
            array('id' =>559, 'name'=> 'Morning blue', 'hex'=> '#8DA399'),
            array('id' =>560, 'name'=> 'Moss green', 'hex'=> '#8A9A5B'),
            array('id' =>561, 'name'=> 'Mountain Meadow', 'hex'=> '#30BA8F'),
            array('id' =>562, 'name'=> 'Mountbatten pink', 'hex'=> '#997A8D'),
            array('id' =>563, 'name'=> 'MSU green', 'hex'=> '#18453B'),
            array('id' =>564, 'name'=> 'Mulberry', 'hex'=> '#C54B8C'),
            array('id' =>565, 'name'=> 'Mulberry-Crayola', 'hex'=> '#C8509B'),
            array('id' =>566, 'name'=> 'Mustard', 'hex'=> '#FFDB58'),
            array('id' =>567, 'name'=> 'Myrtle green', 'hex'=> '#317873'),
            array('id' =>568, 'name'=> 'Mystic', 'hex'=> '#D65282'),
            array('id' =>569, 'name'=> 'Mystic maroon', 'hex'=> '#AD4379'),
            array('id' =>570, 'name'=> 'Nadeshiko pink', 'hex'=> '#F6ADC6'),
            array('id' =>571, 'name'=> 'Naples yellow', 'hex'=> '#FADA5E'),
            array('id' =>572, 'name'=> 'Navajo white', 'hex'=> '#FFDEAD'),
            array('id' =>573, 'name'=> 'Navy blue', 'hex'=> '#000080'),
            array('id' =>574, 'name'=> 'Navy blue-Crayola', 'hex'=> '#1974D2'),
            array('id' =>575, 'name'=> 'Neon blue', 'hex'=> '#4666FF'),
            array('id' =>576, 'name'=> 'Neon green', 'hex'=> '#39FF14'),
            array('id' =>577, 'name'=> 'New York pink', 'hex'=> '#D7837F'),
            array('id' =>578, 'name'=> 'Nickel', 'hex'=> '#727472'),
            array('id' =>579, 'name'=> 'Non-photo blue', 'hex'=> '#A4DDED'),
            array('id' =>580, 'name'=> 'Nyanza', 'hex'=> '#E9FFDB'),
            array('id' =>581, 'name'=> 'Ocean Blue', 'hex'=> '#4F42B5'),
            array('id' =>582, 'name'=> 'Ocean green', 'hex'=> '#48BF91'),
            array('id' =>583, 'name'=> 'Ochre', 'hex'=> '#CC7722'),
            array('id' =>584, 'name'=> 'Old burgundy', 'hex'=> '#43302E'),
            array('id' =>585, 'name'=> 'Old gold', 'hex'=> '#CFB53B'),
            array('id' =>586, 'name'=> 'Old lace', 'hex'=> '#FDF5E6'),
            array('id' =>587, 'name'=> 'Old lavender', 'hex'=> '#796878'),
            array('id' =>588, 'name'=> 'Old mauve', 'hex'=> '#673147'),
            array('id' =>589, 'name'=> 'Old rose', 'hex'=> '#C08081'),
            array('id' =>590, 'name'=> 'Old silver', 'hex'=> '#848482'),
            array('id' =>591, 'name'=> 'Olive', 'hex'=> '#808000'),
            array('id' =>592, 'name'=> 'Olive Drab-#3', 'hex'=> '#6B8E23'),
            array('id' =>593, 'name'=> 'Olive Drab #7', 'hex'=> '#3C341F'),
            array('id' =>594, 'name'=> 'Olive green', 'hex'=> '#B5B35C'),
            array('id' =>595, 'name'=> 'Olivine', 'hex'=> '#9AB973'),
            array('id' =>596, 'name'=> 'Onyx', 'hex'=> '#353839'),
            array('id' =>597, 'name'=> 'Opal', 'hex'=> '#A8C3BC'),
            array('id' =>598, 'name'=> 'Opera mauve', 'hex'=> '#B784A7'),
            array('id' =>599, 'name'=> 'Orange', 'hex'=> '#FF7F00'),
            array('id' =>600, 'name'=> 'Orange-Crayola', 'hex'=> '#FF7538'),
            array('id' =>601, 'name'=> 'Orange-Pantone', 'hex'=> '#FF5800'),
            array('id' =>602, 'name'=> 'Orange-web', 'hex'=> '#FFA500'),
            array('id' =>603, 'name'=> 'Orange peel', 'hex'=> '#FF9F00'),
            array('id' =>604, 'name'=> 'Orange-red', 'hex'=> '#FF681F'),
            array('id' =>605, 'name'=> 'Orange-red-Crayola', 'hex'=> '#FF5349'),
            array('id' =>606, 'name'=> 'Orange soda', 'hex'=> '#FA5B3D'),
            array('id' =>607, 'name'=> 'Orange-yellow', 'hex'=> '#F5BD1F'),
            array('id' =>608, 'name'=> 'Orange-yellow-Crayola', 'hex'=> '#F8D568'),
            array('id' =>609, 'name'=> 'Orchid', 'hex'=> '#DA70D6'),
            array('id' =>610, 'name'=> 'Orchid pink', 'hex'=> '#F2BDCD'),
            array('id' =>611, 'name'=> 'Orchid-Crayola', 'hex'=> '#E29CD2'),
            array('id' =>612, 'name'=> 'Outer space-Crayola', 'hex'=> '#2D383A'),
            array('id' =>613, 'name'=> 'Outrageous Orange', 'hex'=> '#FF6E4A'),
            array('id' =>614, 'name'=> 'Oxblood', 'hex'=> '#800020'),
            array('id' =>615, 'name'=> 'Oxford blue', 'hex'=> '#002147'),
            array('id' =>616, 'name'=> 'OU Crimson red', 'hex'=> '#841617'),
            array('id' =>617, 'name'=> 'Pacific blue', 'hex'=> '#1CA9C9'),
            array('id' =>618, 'name'=> 'Pakistan green', 'hex'=> '#006600'),
            array('id' =>619, 'name'=> 'Palatinate purple', 'hex'=> '#682860'),
            array('id' =>620, 'name'=> 'Pale aqua', 'hex'=> '#BCD4E6'),
            array('id' =>621, 'name'=> 'Pale cerulean', 'hex'=> '#9BC4E2'),
            array('id' =>622, 'name'=> 'Pale pink', 'hex'=> '#FADADD'),
            array('id' =>623, 'name'=> 'Pale purple-Pantone', 'hex'=> '#FAE6FA'),
            array('id' =>624, 'name'=> 'Pale silver', 'hex'=> '#C9C0BB'),
            array('id' =>625, 'name'=> 'Pale spring bud', 'hex'=> '#ECEBBD'),
            array('id' =>626, 'name'=> 'Pansy purple', 'hex'=> '#78184A'),
            array('id' =>627, 'name'=> 'Paolo Veronese green', 'hex'=> '#009B7D'),
            array('id' =>628, 'name'=> 'Papaya whip', 'hex'=> '#FFEFD5'),
            array('id' =>629, 'name'=> 'Paradise pink', 'hex'=> '#E63E62'),
            array('id' =>630, 'name'=> 'Paris Green', 'hex'=> '#50C878'),
            array('id' =>631, 'name'=> 'Pastel pink', 'hex'=> '#DEA5A4'),
            array('id' =>632, 'name'=> 'Patriarch', 'hex'=> '#800080'),
            array('id' =>633, 'name'=> 'Payne S grey', 'hex'=> '#536878'),
            array('id' =>634, 'name'=> 'Peach', 'hex'=> '#FFE5B4'),
            array('id' =>635, 'name'=> 'Peach-Crayola', 'hex'=> '#FFCBA4'),
            array('id' =>636, 'name'=> 'Peach puff', 'hex'=> '#FFDAB9'),
            array('id' =>637, 'name'=> 'Pear', 'hex'=> '#D1E231'),
            array('id' =>638, 'name'=> 'Pearly purple', 'hex'=> '#B768A2'),
            array('id' =>639, 'name'=> 'Periwinkle', 'hex'=> '#CCCCFF'),
            array('id' =>640, 'name'=> 'Periwinkle-Crayola', 'hex'=> '#C3CDE6'),
            array('id' =>641, 'name'=> 'Permanent Geranium Lake', 'hex'=> '#E12C2C'),
            array('id' =>642, 'name'=> 'Persian blue', 'hex'=> '#1C39BB'),
            array('id' =>643, 'name'=> 'Persian green', 'hex'=> '#00A693'),
            array('id' =>644, 'name'=> 'Persian indigo', 'hex'=> '#32127A'),
            array('id' =>645, 'name'=> 'Persian orange', 'hex'=> '#D99058'),
            array('id' =>646, 'name'=> 'Persian pink', 'hex'=> '#F77FBE'),
            array('id' =>647, 'name'=> 'Persian plum', 'hex'=> '#701C1C'),
            array('id' =>648, 'name'=> 'Persian red', 'hex'=> '#CC3333'),
            array('id' =>649, 'name'=> 'Persian rose', 'hex'=> '#FE28A2'),
            array('id' =>650, 'name'=> 'Persimmon', 'hex'=> '#EC5800'),
            array('id' =>651, 'name'=> 'Pewter Blue', 'hex'=> '#8BA8B7'),
            array('id' =>652, 'name'=> 'Phlox', 'hex'=> '#DF00FF'),
            array('id' =>653, 'name'=> 'Phthalo blue', 'hex'=> '#000F89'),
            array('id' =>654, 'name'=> 'Phthalo green', 'hex'=> '#123524'),
            array('id' =>655, 'name'=> 'Picotee blue', 'hex'=> '#2E2787'),
            array('id' =>656, 'name'=> 'Pictorial carmine', 'hex'=> '#C30B4E'),
            array('id' =>657, 'name'=> 'Piggy pink', 'hex'=> '#FDDDE6'),
            array('id' =>658, 'name'=> 'Pine green', 'hex'=> '#01796F'),
            array('id' =>659, 'name'=> 'Pine tree', 'hex'=> '#2A2F23'),
            array('id' =>660, 'name'=> 'Pink', 'hex'=> '#FFC0CB'),
            array('id' =>661, 'name'=> 'Pink-Pantone', 'hex'=> '#D74894'),
            array('id' =>662, 'name'=> 'Pink flamingo', 'hex'=> '#FC74FD'),
            array('id' =>663, 'name'=> 'Pink lace', 'hex'=> '#FFDDF4'),
            array('id' =>664, 'name'=> 'Pink lavender', 'hex'=> '#D8B2D1'),
            array('id' =>665, 'name'=> 'Pink Sherbet', 'hex'=> '#F78FA7'),
            array('id' =>666, 'name'=> 'Pistachio', 'hex'=> '#93C572'),
            array('id' =>667, 'name'=> 'Platinum', 'hex'=> '#E5E4E2'),
            array('id' =>668, 'name'=> 'Plum', 'hex'=> '#8E4585'),
            array('id' =>669, 'name'=> 'Plum-web', 'hex'=> '#DDA0DD'),
            array('id' =>670, 'name'=> 'Plump Purple', 'hex'=> '#5946B2'),
            array('id' =>671, 'name'=> 'Polished Pine', 'hex'=> '#5DA493'),
            array('id' =>672, 'name'=> 'Pomp and Power', 'hex'=> '#86608E'),
            array('id' =>673, 'name'=> 'Popstar', 'hex'=> '#BE4F62'),
            array('id' =>674, 'name'=> 'Portland Orange', 'hex'=> '#FF5A36'),
            array('id' =>675, 'name'=> 'Powder blue', 'hex'=> '#B0E0E6'),
            array('id' =>676, 'name'=> 'Princeton orange', 'hex'=> '#F58025'),
            array('id' =>677, 'name'=> 'Prune', 'hex'=> '#701C1C'),
            array('id' =>678, 'name'=> 'Prussian blue', 'hex'=> '#003153'),
            array('id' =>679, 'name'=> 'Psychedelic purple', 'hex'=> '#DF00FF'),
            array('id' =>680, 'name'=> 'Puce', 'hex'=> '#CC8899'),
            array('id' =>681, 'name'=> 'Pullman Brown-UPS Brown', 'hex'=> '#644117'),
            array('id' =>682, 'name'=> 'Pumpkin', 'hex'=> '#FF7518'),
            array('id' =>683, 'name'=> 'Purple', 'hex'=> '#6A0DAD'),
            array('id' =>684, 'name'=> 'Purple-web', 'hex'=> '#800080'),
            array('id' =>685, 'name'=> 'Purple-Munsell', 'hex'=> '#9F00C5'),
            array('id' =>686, 'name'=> 'Purple-X11', 'hex'=> '#A020F0'),
            array('id' =>687, 'name'=> 'Purple mountain majesty', 'hex'=> '#9678B6'),
            array('id' =>688, 'name'=> 'Purple navy', 'hex'=> '#4E5180'),
            array('id' =>689, 'name'=> 'Purple pizzazz', 'hex'=> '#FE4EDA'),
            array('id' =>690, 'name'=> 'Purple Plum', 'hex'=> '#9C51B6'),
            array('id' =>691, 'name'=> 'Purpureus', 'hex'=> '#9A4EAE'),
            array('id' =>692, 'name'=> 'Queen blue', 'hex'=> '#436B95'),
            array('id' =>693, 'name'=> 'Queen pink', 'hex'=> '#E8CCD7'),
            array('id' =>694, 'name'=> 'Quick Silver', 'hex'=> '#A6A6A6'),
            array('id' =>695, 'name'=> 'Quinacridone magenta', 'hex'=> '#8E3A59'),
            array('id' =>696, 'name'=> 'Radical Red', 'hex'=> '#FF355E'),
            array('id' =>697, 'name'=> 'Raisin black', 'hex'=> '#242124'),
            array('id' =>698, 'name'=> 'Rajah', 'hex'=> '#FBAB60'),
            array('id' =>699, 'name'=> 'Raspberry', 'hex'=> '#E30B5D'),
            array('id' =>700, 'name'=> 'Raspberry glace', 'hex'=> '#915F6D'),
            array('id' =>701, 'name'=> 'Raspberry rose', 'hex'=> '#B3446C'),
            array('id' =>702, 'name'=> 'Raw Sienna', 'hex'=> '#D68A59'),
            array('id' =>703, 'name'=> 'Raw umber', 'hex'=> '#826644'),
            array('id' =>704, 'name'=> 'Razzle dazzle rose', 'hex'=> '#FF33CC'),
            array('id' =>705, 'name'=> 'Razzmatazz', 'hex'=> '#E3256B'),
            array('id' =>706, 'name'=> 'Razzmic Berry', 'hex'=> '#8D4E85'),
            array('id' =>707, 'name'=> 'Rebecca Purple', 'hex'=> '#663399'),
            array('id' =>708, 'name'=> 'Red', 'hex'=> '#FF0000'),
            array('id' =>709, 'name'=> 'Red-Crayola', 'hex'=> '#EE204D'),
            array('id' =>710, 'name'=> 'Red-Munsell', 'hex'=> '#F2003C'),
            array('id' =>711, 'name'=> 'Red-NCS', 'hex'=> '#C40233'),
            array('id' =>712, 'name'=> 'Red-Pantone', 'hex'=> '#ED2939'),
            array('id' =>713, 'name'=> 'Red-pigment', 'hex'=> '#ED1C24'),
            array('id' =>714, 'name'=> 'Red-RYB', 'hex'=> '#FE2712'),
            array('id' =>715, 'name'=> 'Red-orange', 'hex'=> '#FF5349'),
            array('id' =>716, 'name'=> 'Red-orange-Crayola', 'hex'=> '#FF681F'),
            array('id' =>717, 'name'=> 'Red-orange-Color wheel', 'hex'=> '#FF4500'),
            array('id' =>718, 'name'=> 'Red-purple', 'hex'=> '#E40078'),
            array('id' =>719, 'name'=> 'Red Salsa', 'hex'=> '#FD3A4A'),
            array('id' =>720, 'name'=> 'Red-violet', 'hex'=> '#C71585'),
            array('id' =>721, 'name'=> 'Red-violet-Crayola', 'hex'=> '#C0448F'),
            array('id' =>722, 'name'=> 'Red-violet-Color wheel', 'hex'=> '#922B3E'),
            array('id' =>723, 'name'=> 'Redwood', 'hex'=> '#A45A52'),
            array('id' =>724, 'name'=> 'Resolution blue', 'hex'=> '#002387'),
            array('id' =>725, 'name'=> 'Rhythm', 'hex'=> '#777696'),
            array('id' =>726, 'name'=> 'Rich black', 'hex'=> '#004040'),
            array('id' =>727, 'name'=> 'Rich black-FOGRA29', 'hex'=> '#010B13'),
            array('id' =>728, 'name'=> 'Rich black-FOGRA39', 'hex'=> '#010203'),
            array('id' =>729, 'name'=> 'Rifle green', 'hex'=> '#444C38'),
            array('id' =>730, 'name'=> 'Robin egg blue', 'hex'=> '#00CCCC'),
            array('id' =>731, 'name'=> 'Rocket metallic', 'hex'=> '#8A7F80'),
            array('id' =>732, 'name'=> 'Roman silver', 'hex'=> '#838996'),
            array('id' =>733, 'name'=> 'Rose', 'hex'=> '#FF007F'),
            array('id' =>734, 'name'=> 'Rose bonbon', 'hex'=> '#F9429E'),
            array('id' =>735, 'name'=> 'Rose Dust', 'hex'=> '#9E5E6F'),
            array('id' =>736, 'name'=> 'Rose ebony', 'hex'=> '#674846'),
            array('id' =>737, 'name'=> 'Rose madder', 'hex'=> '#E32636'),
            array('id' =>738, 'name'=> 'Rose pink', 'hex'=> '#FF66CC'),
            array('id' =>739, 'name'=> 'Rose quartz', 'hex'=> '#AA98A9'),
            array('id' =>740, 'name'=> 'Rose red', 'hex'=> '#C21E56'),
            array('id' =>741, 'name'=> 'Rose taupe', 'hex'=> '#905D5D'),
            array('id' =>742, 'name'=> 'Rose vale', 'hex'=> '#AB4E52'),
            array('id' =>743, 'name'=> 'Rosewood', 'hex'=> '#65000B'),
            array('id' =>744, 'name'=> 'Rosso corsa', 'hex'=> '#D40000'),
            array('id' =>745, 'name'=> 'Rosy brown', 'hex'=> '#BC8F8F'),
            array('id' =>746, 'name'=> 'Royal blue-dark', 'hex'=> '#002366'),
            array('id' =>747, 'name'=> 'Royal blue-light', 'hex'=> '#4169E1'),
            array('id' =>748, 'name'=> 'Royal purple', 'hex'=> '#7851A9'),
            array('id' =>749, 'name'=> 'Royal yellow', 'hex'=> '#FADA5E'),
            array('id' =>750, 'name'=> 'Ruber', 'hex'=> '#CE4676'),
            array('id' =>751, 'name'=> 'Rubine red', 'hex'=> '#D10056'),
            array('id' =>752, 'name'=> 'Ruby', 'hex'=> '#E0115F'),
            array('id' =>753, 'name'=> 'Ruby red', 'hex'=> '#9B111E'),
            array('id' =>754, 'name'=> 'Rufous', 'hex'=> '#A81C07'),
            array('id' =>755, 'name'=> 'Russet', 'hex'=> '#80461B'),
            array('id' =>756, 'name'=> 'Russian green', 'hex'=> '#679267'),
            array('id' =>757, 'name'=> 'Russian violet', 'hex'=> '#32174D'),
            array('id' =>758, 'name'=> 'Rust', 'hex'=> '#B7410E'),
            array('id' =>759, 'name'=> 'Rusty red', 'hex'=> '#DA2C43'),
            array('id' =>760, 'name'=> 'Sacramento State green', 'hex'=> '#043927'),
            array('id' =>761, 'name'=> 'Saddle brown', 'hex'=> '#8B4513'),
            array('id' =>762, 'name'=> 'Safety orange', 'hex'=> '#FF7800'),
            array('id' =>763, 'name'=> 'Safety orange-blaze orange', 'hex'=> '#FF6700'),
            array('id' =>764, 'name'=> 'Safety yellow', 'hex'=> '#EED202'),
            array('id' =>765, 'name'=> 'Saffron', 'hex'=> '#F4C430'),
            array('id' =>766, 'name'=> 'Sage', 'hex'=> '#BCB88A'),
            array('id' =>767, 'name'=> 'St. Patrick S blue', 'hex'=> '#23297A'),
            array('id' =>768, 'name'=> 'Salmon', 'hex'=> '#FA8072'),
            array('id' =>769, 'name'=> 'Salmon pink', 'hex'=> '#FF91A4'),
            array('id' =>770, 'name'=> 'Sand', 'hex'=> '#C2B280'),
            array('id' =>771, 'name'=> 'Sand dune', 'hex'=> '#967117'),
            array('id' =>772, 'name'=> 'Sandy brown', 'hex'=> '#F4A460'),
            array('id' =>773, 'name'=> 'Sap green', 'hex'=> '#507D2A'),
            array('id' =>774, 'name'=> 'Sapphire', 'hex'=> '#0F52BA'),
            array('id' =>775, 'name'=> 'Sapphire blue', 'hex'=> '#0067A5'),
            array('id' =>776, 'name'=> 'Sapphire-Crayola', 'hex'=> '#0067A5'),
            array('id' =>777, 'name'=> 'Satin sheen gold', 'hex'=> '#CBA135'),
            array('id' =>778, 'name'=> 'Scarlet', 'hex'=> '#FF2400'),
            array('id' =>779, 'name'=> 'Schauss pink', 'hex'=> '#FF91AF'),
            array('id' =>780, 'name'=> 'School bus yellow', 'hex'=> '#FFD800'),
            array('id' =>781, 'name'=> 'Screamin- Green', 'hex'=> '#66FF66'),
            array('id' =>782, 'name'=> 'Sea green', 'hex'=> '#2E8B57'),
            array('id' =>783, 'name'=> 'Sea green-Crayola', 'hex'=> '#00FFCD'),
            array('id' =>784, 'name'=> 'Seal brown', 'hex'=> '#59260B'),
            array('id' =>785, 'name'=> 'Seashell', 'hex'=> '#FFF5EE'),
            array('id' =>786, 'name'=> 'Selective yellow', 'hex'=> '#FFBA00'),
            array('id' =>787, 'name'=> 'Sepia', 'hex'=> '#704214'),
            array('id' =>788, 'name'=> 'Shadow', 'hex'=> '#8A795D'),
            array('id' =>789, 'name'=> 'Shadow blue', 'hex'=> '#778BA5'),
            array('id' =>790, 'name'=> 'Shamrock green', 'hex'=> '#009E60'),
            array('id' =>791, 'name'=> 'Sheen green', 'hex'=> '#8FD400'),
            array('id' =>792, 'name'=> 'Shimmering Blush', 'hex'=> '#D98695'),
            array('id' =>793, 'name'=> 'Shiny Shamrock', 'hex'=> '#5FA778'),
            array('id' =>794, 'name'=> 'Shocking pink', 'hex'=> '#FC0FC0'),
            array('id' =>795, 'name'=> 'Shocking pink-Crayola', 'hex'=> '#FF6FFF'),
            array('id' =>796, 'name'=> 'Sienna', 'hex'=> '#882D17'),
            array('id' =>797, 'name'=> 'Silver', 'hex'=> '#C0C0C0'),
            array('id' =>798, 'name'=> 'Silver-Crayola', 'hex'=> '#C9C0BB'),
            array('id' =>799, 'name'=> 'Silver-Metallic', 'hex'=> '#AAA9AD'),
            array('id' =>800, 'name'=> 'Silver chalice', 'hex'=> '#ACACAC'),
            array('id' =>801, 'name'=> 'Silver pink', 'hex'=> '#C4AEAD'),
            array('id' =>802, 'name'=> 'Silver sand', 'hex'=> '#BFC1C2'),
            array('id' =>803, 'name'=> 'Sinopia', 'hex'=> '#CB410B'),
            array('id' =>804, 'name'=> 'Sizzling Red', 'hex'=> '#FF3855'),
            array('id' =>805, 'name'=> 'Sizzling Sunrise', 'hex'=> '#FFDB00'),
            array('id' =>806, 'name'=> 'Skobeloff', 'hex'=> '#007474'),
            array('id' =>807, 'name'=> 'Sky blue', 'hex'=> '#87CEEB'),
            array('id' =>808, 'name'=> 'Sky blue-Crayola', 'hex'=> '#76D7EA'),
            array('id' =>809, 'name'=> 'Sky magenta', 'hex'=> '#CF71AF'),
            array('id' =>810, 'name'=> 'Slate blue', 'hex'=> '#6A5ACD'),
            array('id' =>811, 'name'=> 'Slate gray', 'hex'=> '#708090'),
            array('id' =>812, 'name'=> 'Slimy green', 'hex'=> '#299617'),
            array('id' =>813, 'name'=> 'Smitten', 'hex'=> '#C84186'),
            array('id' =>814, 'name'=> 'Smoky black', 'hex'=> '#100C08'),
            array('id' =>815, 'name'=> 'Snow', 'hex'=> '#FFFAFA'),
            array('id' =>816, 'name'=> 'Solid pink', 'hex'=> '#893843'),
            array('id' =>817, 'name'=> 'Sonic silver', 'hex'=> '#757575'),
            array('id' =>818, 'name'=> 'Space cadet', 'hex'=> '#1D2951'),
            array('id' =>819, 'name'=> 'Spanish bistre', 'hex'=> '#807532'),
            array('id' =>820, 'name'=> 'Spanish blue', 'hex'=> '#0070B8'),
            array('id' =>821, 'name'=> 'Spanish carmine', 'hex'=> '#D10047'),
            array('id' =>822, 'name'=> 'Spanish gray', 'hex'=> '#989898'),
            array('id' =>823, 'name'=> 'Spanish green', 'hex'=> '#009150'),
            array('id' =>824, 'name'=> 'Spanish orange', 'hex'=> '#E86100'),
            array('id' =>825, 'name'=> 'Spanish pink', 'hex'=> '#F7BFBE'),
            array('id' =>826, 'name'=> 'Spanish red', 'hex'=> '#E60026'),
            array('id' =>827, 'name'=> 'Spanish sky blue', 'hex'=> '#00FFFF'),
            array('id' =>828, 'name'=> 'Spanish violet', 'hex'=> '#4C2882'),
            array('id' =>829, 'name'=> 'Spanish viridian', 'hex'=> '#007F5C'),
            array('id' =>830, 'name'=> 'Spring bud', 'hex'=> '#A7FC00'),
            array('id' =>831, 'name'=> 'Spring Frost', 'hex'=> '#87FF2A'),
            array('id' =>832, 'name'=> 'Spring green', 'hex'=> '#00FF7F'),
            array('id' =>833, 'name'=> 'Spring green-Crayola', 'hex'=> '#ECEBBD'),
            array('id' =>834, 'name'=> 'Star command blue', 'hex'=> '#007BB8'),
            array('id' =>835, 'name'=> 'Steel blue', 'hex'=> '#4682B4'),
            array('id' =>836, 'name'=> 'Steel pink', 'hex'=> '#CC33CC'),
            array('id' =>837, 'name'=> 'Steel Teal', 'hex'=> '#5F8A8B'),
            array('id' =>838, 'name'=> 'Stil de grain yellow', 'hex'=> '#FADA5E'),
            array('id' =>839, 'name'=> 'Straw', 'hex'=> '#E4D96F'),
            array('id' =>840, 'name'=> 'Sugar Plum', 'hex'=> '#914E75'),
            array('id' =>841, 'name'=> 'Sunglow', 'hex'=> '#FFCC33'),
            array('id' =>842, 'name'=> 'Sunray', 'hex'=> '#E3AB57'),
            array('id' =>843, 'name'=> 'Sunset', 'hex'=> '#FAD6A5'),
            array('id' =>844, 'name'=> 'Super pink', 'hex'=> '#CF6BA9'),
            array('id' =>845, 'name'=> 'Sweet Brown', 'hex'=> '#A83731'),
            array('id' =>846, 'name'=> 'Tan', 'hex'=> '#D2B48C'),
            array('id' =>847, 'name'=> 'Tan-Crayola', 'hex'=> '#D99A6C'),
            array('id' =>848, 'name'=> 'Tangerine', 'hex'=> '#F28500'),
            array('id' =>849, 'name'=> 'Tango pink', 'hex'=> '#E4717A'),
            array('id' =>850, 'name'=> 'Tart Orange', 'hex'=> '#FB4D46'),
            array('id' =>851, 'name'=> 'Taupe', 'hex'=> '#483C32'),
            array('id' =>852, 'name'=> 'Taupe gray', 'hex'=> '#8B8589'),
            array('id' =>853, 'name'=> 'Tea green', 'hex'=> '#D0F0C0'),
            array('id' =>854, 'name'=> 'Tea rose', 'hex'=> '#F88379'),
            array('id' =>855, 'name'=> 'Tea rose', 'hex'=> '#F4C2C2'),
            array('id' =>856, 'name'=> 'Teal', 'hex'=> '#008080'),
            array('id' =>857, 'name'=> 'Teal blue', 'hex'=> '#367588'),
            array('id' =>858, 'name'=> 'Telemagenta', 'hex'=> '#CF3476'),
            array('id' =>859, 'name'=> 'Tenné-tawny', 'hex'=> '#CD5700'),
            array('id' =>860, 'name'=> 'Terra cotta', 'hex'=> '#E2725B'),
            array('id' =>861, 'name'=> 'Thistle', 'hex'=> '#D8BFD8'),
            array('id' =>862, 'name'=> 'Thulian pink', 'hex'=> '#DE6FA1'),
            array('id' =>863, 'name'=> 'Tickle Me Pink', 'hex'=> '#FC89AC'),
            array('id' =>864, 'name'=> 'Tiffany Blue', 'hex'=> '#0ABAB5'),
            array('id' =>865, 'name'=> 'Timberwolf', 'hex'=> '#DBD7D2'),
            array('id' =>866, 'name'=> 'Titanium yellow', 'hex'=> '#EEE600'),
            array('id' =>867, 'name'=> 'Tomato', 'hex'=> '#FF6347'),
            array('id' =>868, 'name'=> 'Tropical rain forest', 'hex'=> '#00755E'),
            array('id' =>869, 'name'=> 'True Blue', 'hex'=> '#2D68C4'),
            array('id' =>870, 'name'=> 'Trypan Blue', 'hex'=> '#1C05B3'),
            array('id' =>871, 'name'=> 'Tufts blue', 'hex'=> '#3E8EDE'),
            array('id' =>872, 'name'=> 'Tumbleweed', 'hex'=> '#DEAA88'),
            array('id' =>873, 'name'=> 'Turquoise', 'hex'=> '#40E0D0'),
            array('id' =>874, 'name'=> 'Turquoise blue', 'hex'=> '#00FFEF'),
            array('id' =>875, 'name'=> 'Turquoise green', 'hex'=> '#A0D6B4'),
            array('id' =>876, 'name'=> 'Turtle green', 'hex'=> '#8A9A5B'),
            array('id' =>877, 'name'=> 'Tuscan', 'hex'=> '#FAD6A5'),
            array('id' =>878, 'name'=> 'Tuscan brown', 'hex'=> '#6F4E37'),
            array('id' =>879, 'name'=> 'Tuscan red', 'hex'=> '#7C4848'),
            array('id' =>880, 'name'=> 'Tuscan tan', 'hex'=> '#A67B5B'),
            array('id' =>881, 'name'=> 'Tuscany', 'hex'=> '#C09999'),
            array('id' =>882, 'name'=> 'Twilight lavender', 'hex'=> '#8A496B'),
            array('id' =>883, 'name'=> 'Tyrian purple', 'hex'=> '#66023C'),
            array('id' =>884, 'name'=> 'UA blue', 'hex'=> '#0033AA'),
            array('id' =>885, 'name'=> 'UA red', 'hex'=> '#D9004C'),
            array('id' =>886, 'name'=> 'Ultramarine', 'hex'=> '#3F00FF'),
            array('id' =>887, 'name'=> 'Ultramarine blue', 'hex'=> '#4166F5'),
            array('id' =>888, 'name'=> 'Ultra pink', 'hex'=> '#FF6FFF'),
            array('id' =>889, 'name'=> 'Ultra red', 'hex'=> '#FC6C85'),
            array('id' =>890, 'name'=> 'Umber', 'hex'=> '#635147'),
            array('id' =>891, 'name'=> 'Unbleached silk', 'hex'=> '#FFDDCA'),
            array('id' =>892, 'name'=> 'United Nations blue', 'hex'=> '#5B92E5'),
            array('id' =>893, 'name'=> 'Unmellow yellow', 'hex'=> '#FFFF66'),
            array('id' =>894, 'name'=> 'UP Forest green', 'hex'=> '#014421'),
            array('id' =>895, 'name'=> 'UP maroon', 'hex'=> '#7B1113'),
            array('id' =>896, 'name'=> 'Upsdell red', 'hex'=> '#AE2029'),
            array('id' =>897, 'name'=> 'Uranian blue', 'hex'=> '#AFDBF5'),
            array('id' =>898, 'name'=> 'USAFA blue', 'hex'=> '#004F98'),
            array('id' =>899, 'name'=> 'Van Dyke brown', 'hex'=> '#664228'),
            array('id' =>900, 'name'=> 'Vanilla', 'hex'=> '#F3E5AB'),
            array('id' =>901, 'name'=> 'Vanilla ice', 'hex'=> '#F38FA9'),
            array('id' =>902, 'name'=> 'Vegas gold', 'hex'=> '#C5B358'),
            array('id' =>903, 'name'=> 'Venetian red', 'hex'=> '#C80815'),
            array('id' =>904, 'name'=> 'Verdigris', 'hex'=> '#43B3AE'),
            array('id' =>905, 'name'=> 'Vermilion', 'hex'=> '#E34234'),
            array('id' =>906, 'name'=> 'Vermilion', 'hex'=> '#D9381E'),
            array('id' =>907, 'name'=> 'Veronica', 'hex'=> '#A020F0'),
            array('id' =>908, 'name'=> 'Violet', 'hex'=> '#8F00FF'),
            array('id' =>909, 'name'=> 'Violet-color wheel', 'hex'=> '#7F00FF'),
            array('id' =>910, 'name'=> 'Violet-crayola', 'hex'=> '#963D7F'),
            array('id' =>911, 'name'=> 'Violet-RYB', 'hex'=> '#8601AF'),
            array('id' =>912, 'name'=> 'Violet-web', 'hex'=> '#EE82EE'),
            array('id' =>913, 'name'=> 'Violet-blue', 'hex'=> '#324AB2'),
            array('id' =>914, 'name'=> 'Violet-blue-Crayola', 'hex'=> '#766EC8'),
            array('id' =>915, 'name'=> 'Violet-red', 'hex'=> '#F75394'),
            array('id' =>916, 'name'=> 'Viridian', 'hex'=> '#40826D'),
            array('id' =>917, 'name'=> 'Viridian green', 'hex'=> '#009698'),
            array('id' =>918, 'name'=> 'Vivid burgundy', 'hex'=> '#9F1D35'),
            array('id' =>919, 'name'=> 'Vivid sky blue', 'hex'=> '#00CCFF'),
            array('id' =>920, 'name'=> 'Vivid tangerine', 'hex'=> '#FFA089'),
            array('id' =>921, 'name'=> 'Vivid violet', 'hex'=> '#9F00FF'),
            array('id' =>922, 'name'=> 'Volt', 'hex'=> '#CEFF00'),
            array('id' =>923, 'name'=> 'Warm black', 'hex'=> '#004242'),
            array('id' =>924, 'name'=> 'Wheat', 'hex'=> '#F5DEB3'),
            array('id' =>925, 'name'=> 'White', 'hex'=> '#FFFFFF'),
            array('id' =>926, 'name'=> 'Wild blue yonder', 'hex'=> '#A2ADD0'),
            array('id' =>927, 'name'=> 'Wild orchid', 'hex'=> '#D470A2'),
            array('id' =>928, 'name'=> 'Wild Strawberry', 'hex'=> '#FF43A4'),
            array('id' =>929, 'name'=> 'Wild watermelon', 'hex'=> '#FC6C85'),
            array('id' =>930, 'name'=> 'Windsor tan', 'hex'=> '#A75502'),
            array('id' =>931, 'name'=> 'Wine', 'hex'=> '#722F37'),
            array('id' =>932, 'name'=> 'Wine dregs', 'hex'=> '#673147'),
            array('id' =>933, 'name'=> 'Winter Sky', 'hex'=> '#FF007C'),
            array('id' =>934, 'name'=> 'Wintergreen Dream', 'hex'=> '#56887D'),
            array('id' =>935, 'name'=> 'Wisteria', 'hex'=> '#C9A0DC'),
            array('id' =>936, 'name'=> 'Wood brown', 'hex'=> '#C19A6B'),
            array('id' =>937, 'name'=> 'Xanthic', 'hex'=> '#EEED09'),
            array('id' =>938, 'name'=> 'Xanadu', 'hex'=> '#738678'),
            array('id' =>939, 'name'=> 'Xiketic', 'hex'=> '#0C020F'),
            array('id' =>940, 'name'=> 'Yale Blue', 'hex'=> '#0F4D92'),
            array('id' =>941, 'name'=> 'Yellow', 'hex'=> '#FFFF00'),
            array('id' =>942, 'name'=> 'Yellow-Crayola', 'hex'=> '#FCE883'),
            array('id' =>943, 'name'=> 'Yellow-Munsell', 'hex'=> '#EFCC00'),
            array('id' =>944, 'name'=> 'Yellow-NCS', 'hex'=> '#FFD300'),
            array('id' =>945, 'name'=> 'Yellow-Pantone', 'hex'=> '#FEDF00'),
            array('id' =>946, 'name'=> 'Yellow-process', 'hex'=> '#FFEF00'),
            array('id' =>947, 'name'=> 'Yellow-RYB', 'hex'=> '#FEFE33'),
            array('id' =>948, 'name'=> 'Yellow-green', 'hex'=> '#9ACD32'),
            array('id' =>949, 'name'=> 'Yellow-green-Crayola', 'hex'=> '#C5E384'),
            array('id' =>950, 'name'=> 'Yellow-green-Color Wheel', 'hex'=> '#30B21A'),
            array('id' =>951, 'name'=> 'Yellow Orange', 'hex'=> '#FFAE42'),
            array('id' =>952, 'name'=> 'Yellow Orange-Color Wheel', 'hex'=> '#FF9505'),
            array('id' =>953, 'name'=> 'Yellow Sunshine', 'hex'=> '#FFF700'),
            array('id' =>954, 'name'=> 'YInMn Blue', 'hex'=> '#2E5090'),
            array('id' =>955, 'name'=> 'Zaffre', 'hex'=> '#0014A8'),
            array('id' =>956, 'name'=> 'Zomp', 'hex'=> '#39A78E'),
        ));
    
            
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('colors');
    }
}
